### ISSUE TITLE
[BUG] LDAP authentication with group is broken

### ISSUE THREAD

**Issue by beza2000** [WillyXJ/facileManager#533]
facileManager v4.0.3
fmDNS v4.1.0

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**
Normal work

**(BUG | ISSUE) Steps to reproduce:**
Now I work with facileManager v3.4 / fmDNS v3.3.1.
I'm testing to move to facileManager v4.0.3 / fmDNS v4.1.0, but LDAP authentication with group don't work.
I have log:
......
[21-Jul-2021 16:07:00 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function fm_login::checkGroupMembership(), 3 passed in /var/www/facileManager/server/fm-modules/facileManager/classes/class_logins.php on line
 691 and exactly 4 expected in /var/www/facileManager/server/fm-modules/facileManager/classes/class_logins.php:679
Stack trace:
#0 /var/www/facileManager/server/fm-modules/facileManager/classes/class_logins.php(691): fm_login->checkGroupMembership(Resource id #23, 'CN=nuxeo_test,O...', 'CN=IT Departmen...')
#1 /var/www/facileManager/server/fm-modules/facileManager/classes/class_logins.php(561): fm_login->checkGroupMembership(Resource id #23, 'CN=user...', 'CN=IT Departmen...', 'memberof')
#2 /var/www/facileManager/server/fm-modules/facileManager/classes/class_logins.php(322): fm_login->doLDAPAuth('user...', 'xxxxx*')
#3 /var/www/facileManager/server/fm-init.php(132): fm_login->checkPassword('user...', 'xxxxxxx*')
#4 /var/www/facileManager/server/index.php(38): require('/var/www/facile...') in /var/www/facileManager/server/fm-modules/facileManager/classes/class_logins.php on line 679

**Comment by WillyXJ** [comment]
It looks like it's line 691 of facileManager/classes/class_logins.php as it's missing a parameter.  Please edit your file and change it to and report back:

```
				elseif ($this->checkGroupMembership($ldap_connect, $entries[0][$ldap_group_attribute][$i], $groupdn, $ldap_group_attribute)) return true;
```

**Comment by beza2000** [comment]
It's working now.
