### ISSUE TITLE
fmDHCP with php7.3

### ISSUE THREAD

**Issue by cm91** [WillyXJ/facileManager#442]
Please prefix your issue title with one of the following: [ISSUE]

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **3.4.1**
{fmDHCP} Version : **0.4.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(ISSUE) Expected Behavior:**
Adding Options should work

**(BUG | ISSUE) Actual Behavior:**

I cannot add any options in fmDHCP since i updated my php version to 7.3

php -v
PHP 7.3.4-1+0~20190412071350.37+stretch~1.gbpabc171 (cli) (built: Apr 12 2019 07:13:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.4-1+0~20190412071350.37+stretch~1.gbpabc171, Copyright (c) 1999-2018, by Zend Technologies

Everytime i add any option (e.g. new host for dhcp reservation) i get this error after clicking apply:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function fm_module_options::validateDefType(), 1 passed in /var/www/facileManager/server/fm-modules/fmDHCP/classes/class_objects.php on line 1022 and exactly 2 expected in /var/www/facileManager/server/fm-modules/fmDHCP/classes/class_options.php:526 Stack trace: #0 /var/www/facileManager/server/fm-modules/fmDHCP/classes/class_objects.php(1022): fm_module_options->validateDefType(Array) #1 /var/www/facileManager/server/fm-modules/fmDHCP/classes/class_pools.php(192): fm_dhcp_objects->validateObjectPost(Array) #2 /var/www/facileManager/server/fm-modules/fmDHCP/classes/class_objects.php(223): fm_dhcp_pools->validatePost(Array) #3 /var/www/facileManager/server/fm-modules/fmDHCP/pages/objects.php(53): fm_dhcp_objects->update(Array, 'pools') #4 /var/www/facileManager/server/fm-modules/fmDHCP/pages/object-pools.php(38): include('/var/www/facile...') #5 /var/www/facileManager/server/index.php(51): include('/var/www/facile...') #6 {main} thrown in /var/www/facileManager/server/fm-modules/fmDHCP/classes/class_options.php on line 526

I installed facilemanager on a server with php7.0 and everything works

**(BUG | ISSUE) Steps to reproduce:**

use fmDHCP on debian stretch with php7.3

**Comment by WillyXJ** [comment]
This is now fixed in [fmDHCP 0.4.2](http://www.facilemanager.com/modules/fmdhcp/) and later.

**Comment by cm91** [comment]
Thank you very much! Just tested and it's working. Regards, Christian
